version: '3'

services:

  fript-api:
    build: .
    container_name: api
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/fript-api
      - /opt/fript-api/node_modules
    #net: host
  
  #fript-web:
  #  build: ../fript-web
